### PR TITLE
Hackathon: Ascii Function

### PR DESCRIPTION
**Pull request by pdaviso**
The ASCII function returns the ascii value of the first character in the string that is passed into it. This pull request includes implementation (in string_functions and built-in specification files), integration (in database_catalog), a C++ test (in string_functions_test), and a Junit test (in FunctionsTest).

### CODE REVIEW

**Comment by pdaviso** [comment]
Reordered existing string functions (lower, ascii, position the only new ones at this point) in alphabetical order

**Comment by apavlo** [comment]
I am getting weird test case failures with your branch. I need to investigate further.

**Comment by pdaviso** [comment]
> I am getting weird test case failures with your branch. I need to investigate further.

Ok. It is passing on my local machine, but originally it did fail when pulling recent changes from the master (specifically in the junit tests - I had to remake). Let me know if I can help at all.

**Comment by jkosh44** [comment]
@pdaviso Do you remember if the final commit, https://github.com/apavlo/terrier/pull/8/commits/f6c267fae4ce4ca3461b39fcf52d8432a3d892f7, does anything other than reorder the functions? Does it change any of the function contents?

**Comment by pdaviso** [comment]
> @pdaviso Do you remember if the final commit, [f6c267f](https://github.com/apavlo/terrier/commit/f6c267fae4ce4ca3461b39fcf52d8432a3d892f7), does anything other than reorder the functions? Does it change any of the function contents?

As far as I am aware, the last commit only reorders the functions. I could be wrong. It looks like the FunctionsTest.java file was also changed (fixed from C syntax to Java syntax). I think I would have to compare the string_functions.cpp file and string_functions.h with the previous commit to confirm. Would you be willing to do that if it will make a difference?

**Comment by jkosh44** [comment]
> > @pdaviso Do you remember if the final commit, [f6c267f](https://github.com/apavlo/terrier/commit/f6c267fae4ce4ca3461b39fcf52d8432a3d892f7), does anything other than reorder the functions? Does it change any of the function contents?
> 
> As far as I am aware, the last commit only reorders the functions. I could be wrong. It looks like the FunctionsTest.java file was also changed (fixed from C syntax to Java syntax). I think I would have to compare the string_functions.cpp file and string_functions.h with the previous commit to confirm. Would you be willing to do that if it will make a difference?

Yep no worries, I'll compare the two

**Comment by pdaviso** [comment]
> > > @pdaviso Do you remember if the final commit, [f6c267f](https://github.com/apavlo/terrier/commit/f6c267fae4ce4ca3461b39fcf52d8432a3d892f7), does anything other than reorder the functions? Does it change any of the function contents?
> > 
> > 
> > As far as I am aware, the last commit only reorders the functions. I could be wrong. It looks like the FunctionsTest.java file was also changed (fixed from C syntax to Java syntax). I think I would have to compare the string_functions.cpp file and string_functions.h with the previous commit to confirm. Would you be willing to do that if it will make a difference?
> 
> Yep no worries, I'll compare the two

Thank you! I hope you have a good weekend.

**Comment by jkosh44** [comment]
This can now be closed and replaced with #1091

**Pull request closed without merging**
